#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy nginx/nginx.conf

remote=root@discuss.grapheneos.org

rsync -rpcv --chmod=D755,F644 --delete --fsync --preallocate nginx/{nginx.conf,mime.types,snippets,blocked.conf} $remote:/etc/nginx/
rsync -pcv --chmod=D755,F644 --fsync --preallocate my.cnf.d/server.cnf $remote:/etc/my.cnf.d/server.cnf
rsync -rpcv --chmod=D755,F644 --fsync --preallocate php/{php.ini,php-fpm.d} $remote:/etc/php/
rsync -rpcv --chmod=D755,F644 --fsync --preallocate php-legacy/{php.ini,php-fpm.d} $remote:/etc/php-legacy/
rsync -pcv --chmod=755 --fsync --preallocate {flarum-asset-compress,flarum-deploy,remote-backup,stopforumspam-update} $remote:/usr/local/bin/
rsync -pcv --chmod=644 --fsync --preallocate backup-public-key.txt cloud-archive-password.txt flarum-admin@discuss.grapheneos.org:
rsync -pcv --chown root:geoipupdate --chmod=F640 --fsync --preallocate GeoIP.conf $remote:/etc/GeoIP.conf
rsync -prcv --chmod=D755,F644 --fsync --preallocate systemd/system/ $remote:/etc/systemd/system
ssh $remote nginx -s reload
