#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy nginx/nginx.conf

remote=root@discuss.grapheneos.org

rsync -rptcv --fsync --chmod=D755,F644 --delete nginx/{nginx.conf,mime.types,snippets} $remote:/etc/nginx/
rsync -ptcv --fsync --chmod=D755,F644 my.cnf.d/server.cnf $remote:/etc/my.cnf.d/server.cnf
rsync -ptcv --fsync --chmod=D755,F644 php/php.ini $remote:/etc/php/php.ini
rsync -rptcv --fsync --chmod=D755,F644 php/php-fpm.d/ $remote:/etc/php/php-fpm.d
rsync -ptcv --fsync --chmod=D755,F644 php-legacy/php.ini $remote:/etc/php-legacy/php.ini
rsync -rptcv --fsync --chmod=D755,F644 php-legacy/php-fpm.d/ $remote:/etc/php-legacy/php-fpm.d
rsync -ptcv --fsync --chmod=755 {flarum-asset-compress,flarum-deploy,local-backup,remote-backup} $remote:/usr/local/bin/
rsync -prctv --chmod=D755,F644 systemd/system/ $remote:/etc/systemd/system
ssh $remote nginx -s reload

echo
