#!/bin/bash

shopt -s extglob nullglob

cd /opt
find flarum/public/assets/ -name '*.gz' -o -name '*.br' -delete
su flarum-admin -c "rsync -tv flarum-staging/composer.{lock,json} flarum/"
systemctl stop php-fpm
su flarum-admin -c "rsync -tvr --delete flarum-staging/vendor/ flarum/vendor"
systemctl start php-fpm
su flarum -c "php flarum migrate; php flarum cache:clear; php flarum assets:publish"
su flarum -c flarum-asset-compress
