#!/bin/bash

set -o errexit -o nounset -o pipefail

remote=flarum-admin@discuss.grapheneos.org

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
ssh $remote "rm -rf local-backup"
ssh $remote "mkdir local-backup"

ssh $remote "mkdir local-backup/$timestamp"
ssh $remote "mariadb-dump --all-databases --single-transaction > local-backup/$timestamp/all_databases.sql"
ssh $remote "cp /var/lib/valkey/dump.rdb local-backup/$timestamp/"
ssh $remote "rsync -rl --exclude '/storage/cache/*' --exclude '/storage/gdpr-exports/*' --exclude '/storage/sessions/*' --exclude '/storage/tmp/*' /opt/flarum/ local-backup/$timestamp/flarum"
ssh $remote "tar -cC local-backup $timestamp | zstd -9 | age -r \$(cat backup-public-key.txt) -o local-backup/$timestamp.tar.zst.age"
rsync -v --fsync --preallocate $remote:./local-backup/$timestamp.tar.zst.age backup/

ssh $remote "rm -rf local-backup"
