#!/bin/bash

set -o errexit -o nounset -o pipefail

remote=root@discuss.grapheneos.org

timestamp=$(date -u +%Y-%m-%dT%H:%m:%SZ)
ssh $remote "rm -rf local-backup"
ssh $remote "mkdir local-backup"

ssh $remote "mkdir local-backup/$timestamp"
ssh $remote "mysqldump --all-databases --single-transaction > local-backup/$timestamp/all_databases.sql"
ssh $remote "cp -a /opt/flarum local-backup/$timestamp/flarum"
ssh $remote "tar c -C local-backup $timestamp | zstd -9 | age -r \$(cat backup-public-key.txt) -o local-backup/$timestamp.tar.zst.age"
rsync -v $remote:./local-backup/$timestamp.tar.zst.age backup/
