#!/bin/bash

set -o errexit -o nounset -o pipefail

cd /etc/nginx

mode="$1"

[[ $mode == @(daily|hourly) ]] || exit 1

if [[ $mode == daily ]]; then
    curl -sS --fail-with-body https://www.stopforumspam.com/downloads/toxic_ip_cidr.txt | sed 's/$/ stopforumspam-toxic;/' > stopforumspam-toxic_ip_cidr.geo.new
    mv stopforumspam-toxic_ip_cidr.geo.new stopforumspam-toxic_ip_cidr.geo

    curl -sS --fail-with-body https://www.stopforumspam.com/downloads/listed_ip_30.zip | gunzip | sed 's/$/ stopforumspam-30;/' > stopforumspam-listed_ip_30.geo.new
    mv stopforumspam-listed_ip_30.geo.new stopforumspam-listed_ip_30.geo

    curl -sS --fail-with-body https://www.stopforumspam.com/downloads/listed_ip_30_ipv6.zip | gunzip | sed 's|$|/64|' | sed 's/$/ stopforumspam-30;/' > stopforumspam-listed_ip_30_ipv6.geo.new
    mv stopforumspam-listed_ip_30_ipv6.geo.new stopforumspam-listed_ip_30_ipv6.geo
fi

if [[ $mode == hourly ]]; then
    if curl -sS --fail-with-body https://check.torproject.org/torbulkexitlist | sed 's/$/ tor-exit;/' > torbulkexitlist.geo.new; then
        mv torbulkexitlist.geo.new torbulkexitlist.geo
    fi

    curl -sS --fail-with-body https://www.spamhaus.org/drop/drop_v4.json | jq -r 'select(.type == null) | .cidr' | sed 's/$/ spamhaus-drop;/' > spamhaus_drop_v4.geo.new
    mv spamhaus_drop_v4.geo.new spamhaus_drop_v4.geo

    curl -sS --fail-with-body https://www.spamhaus.org/drop/drop_v6.json | jq -r 'select(.type == null) | .cidr' | sed 's/$/ spamhaus-drop;/' > spamhaus_drop_v6.geo.new
    mv spamhaus_drop_v6.geo.new spamhaus_drop_v6.geo

    curl -sS --fail-with-body https://lists.blocklist.de/lists/all.txt | sed 's/$/ blocklist.de;/' > blocklist.de.geo.new
    mv blocklist.de.geo.new blocklist.de.geo

    curl -sS --fail-with-body https://www.stopforumspam.com/downloads/listed_ip_1.zip | gunzip | sed 's/$/ stopforumspam-1;/' > stopforumspam-listed_ip_1.geo.new
    mv stopforumspam-listed_ip_1.geo.new stopforumspam-listed_ip_1.geo

    curl -sS --fail-with-body https://www.stopforumspam.com/downloads/listed_ip_1_ipv6.zip | gunzip | sed 's|$|/64|' | sed 's/$/ stopforumspam-1;/' > stopforumspam-listed_ip_1_ipv6.geo.new
    mv stopforumspam-listed_ip_1_ipv6.geo.new stopforumspam-listed_ip_1_ipv6.geo

    sort -usk 1,1 registration-ip-allowlist-local.geo torbulkexitlist.geo > registration-ip-allowlist.geo.new
    mv registration-ip-allowlist.geo.new registration-ip-allowlist.geo

    sort -usk 1,1 registration-ip-blocklist-local.geo spamhaus_drop_{v4,v6}.geo stopforumspam-toxic_ip_cidr.geo stopforumspam-listed_ip_{1,30}{,_ipv6}.geo blocklist.de.geo > registration-ip-blocklist.geo.new
    mv registration-ip-blocklist.geo.new registration-ip-blocklist.geo
fi
