#!/bin/bash

set -o errexit -o nounset -o pipefail

curl --fail-with-body https://www.stopforumspam.com/downloads/toxic_ip_cidr.txt | awk '{ print $1 " 1;" }' > /etc/nginx/stopforumspam-toxic_ip_cidr.conf.new
mv /etc/nginx/stopforumspam-toxic_ip_cidr.conf.new /etc/nginx/stopforumspam-toxic_ip_cidr.conf
curl --fail-with-body https://www.stopforumspam.com/downloads/bannedips.csv.gz | gunzip | tr ',' '\n' | awk '{ print $1 " 1;" }' > /etc/nginx/stopforumspam-bannedips.conf.new
mv /etc/nginx/stopforumspam-bannedips.conf.new /etc/nginx/stopforumspam-bannedips.conf
nginx -s reload
